version: '3.2'

services:
  bulita:
    build: .
    restart: always
    ports:
      - "8111:9200"
    volumes:
      - ./data/ImageMessage:/usr/app/bulita/packages/server/public/ImageMessage
      - ./data/FileMessage:/usr/app/bulita/packages/server/public/FileMessage
      - ./data/GroupAvatar:/usr/app/bulita/packages/server/public/GroupAvatar



